spring:
 data:
  mongodb:
   database: springbootapi
   uri: mongodb://springbootapi:PSO8Wm0FLJKrpUYkrJWuXAP8ZsImfXLmEfxvIp25tpZZuN15jzkfSieuNZQhUw43ICe2N8lVJHvH3FVaDCqb3w==@springbootapi.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@springbootapi@
